<a href="https://colab.research.google.com/github/HumayDS/Digital-Data-Analytics-spring-2024-/blob/main/Lesson_10_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import statsmodels.formula.api as smf
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [47]:
##Extract dataset
df = pd.read_csv("https://raw.githubusercontent.com/HumayDS/Big-data-analysis/main/diabetes.csv")
df.drop('Unnamed: 0' , axis = 1, inplace = True)
df = df.dropna()
df.head(50)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6      148             72             35        0  33.6   
1             1       85             66             29        0  26.6   
2             8      183             64              0        0  23.3   
3             1       89             66             23       94  28.1   
4             0      137             40             35      168  43.1   
5             5      116             74              0        0  25.6   
6             3       78             50             32       88  31.0   
7            10      115              0              0        0  35.3   
8             2      197             70             45      543  30.5   
9             8      125             96              0        0   0.0   
10            4      110             92              0        0  37.6   
11           10      168             74              0        0  38.0   
12           10      139             80              0        0  27.1   
13            1      189             60             23      846  30.1   
14            5      166             72             19      175  25.8   
15            7      100              0              0        0  30.0   
16            0      118             84             47      230  45.8   
17            7      107             74              0        0  29.6   
18            1      103             30             38       83  43.3   
19            1      115             70             30       96  34.6   
20            3      126             88             41      235  39.3   
21            8       99             84              0        0  35.4   
22            7      196             90              0        0  39.8   
23            9      119             80             35        0  29.0   
24           11      143             94             33      146  36.6   
25           10      125             70             26      115  31.1   
26            7      147             76              0        0  39.4   
27            1       97             66             15      140  23.2   
28           13      145             82             19      110  22.2   
29            5      117             92              0        0  34.1   
30            5      109             75             26        0  36.0   
31            3      158             76             36      245  31.6   
32            3       88             58             11       54  24.8   
33            6       92             92              0        0  19.9   
34           10      122             78             31        0  27.6   
35            4      103             60             33      192  24.0   
36           11      138             76              0        0  33.2   
37            9      102             76             37        0  32.9   
38            2       90             68             42        0  38.2   
39            4      111             72             47      207  37.1   
40            3      180             64             25       70  34.0   
41            7      133             84              0        0  40.2   
42            7      106             92             18        0  22.7   
43            9      171            110             24      240  45.4   
44            7      159             64              0        0  27.4   
45            0      180             66             39        0  42.0   
46            1      146             56              0        0  29.7   
47            2       71             70             27        0  28.0   
48            7      103             66             32        0  39.1   
49            7      105              0              0        0   0.0   

    DiabetesPedigreeFunction  Age  Outcome  
0                      0.627   50        1  
1                      0.351   31        0  
2                      0.672   32        1  
3                      0.167   21        0  
4                      2.288   33        1  
5         

In [48]:
# Get Information of target variable
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [49]:
#Determine x and
y = df["Outcome"]
X = df.drop(["Outcome"], axis=1)

In [50]:
# prompt: create logistic regression y, X ith intercept
X = sm.add_constant(X)
logit_model = sm.Logit(y, X)
result = logit_model.fit()


Optimization terminated successfully.
         Current function value: 0.470993
         Iterations 6


In [51]:
#Cretae Log regression with statsmodel (For interprete )
loj = sm.Logit(y, X)
loj_model= loj.fit()
loj_model.summary()

Optimization terminated successfully.
         Current function value: 0.470993
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  768
Model:                          Logit   Df Residuals:                      759
Method:                           MLE   Df Model:                            8
Date:                Mon, 06 May 2024   Pseudo R-squ.:                  0.2718
Time:                        12:13:34   Log-Likelihood:                -361.72
converged:                       True   LL-Null:                       -496.74
Covariance Type:            nonrobust   LLR p-value:                 9.652e-54
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -8.4047      0.717    -11.728      0.000      -9.809      -7.000
Pregnancies                  0.1232      0.032      3.840      0.000       0.060       0.186
Glucose                      0.0352      0.004      9.481      0.000       0.028       0.042
BloodPressure               -0.0133      0.005     -2.540      0.011      -0.024      -0.003
SkinThickness                0.0006      0.007      0.090      0.929      -0.013       0.014
Insulin                     -0.0012      0.001     -1.322      0.186      -0.003       0.001
BMI                          0.0897      0.015      5.945      0.000       0.060       0.119
DiabetesPedigreeFunction     0.9452      0.299      3.160      0.002       0.359       1.531
Age                          0.0149      0.009      1.593      0.111      -0.003       0.033
============================================================================================
"""

In [52]:
# Create model with sklearn
from sklearn.linear_model import LogisticRegression
loj = LogisticRegression(solver = "liblinear")
loj_model = loj.fit(X,y)
loj_model

LogisticRegression(solver='liblinear')

In [53]:
#predict y
y_pred = loj_model.predict(X)
y_pred[0:10]

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 0])

In [54]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [55]:
##View predicted probability
y_probs = loj_model.predict_proba(X)
y_probs = y_probs[:,1]
y_probs[0:10]

array([0.67715879, 0.06869281, 0.78206816, 0.06290935, 0.85596858,
       0.18038009, 0.09736403, 0.69439258, 0.69441177, 0.05941365])

In [56]:
#View summary
i = np.arange(len(y_pred))
Data = pd.DataFrame({'y_real' : pd.Series(y, index=i),'y_pred' : pd.Series(y_pred, index = i), 'y_probs' : pd.Series(y_probs, index = i)})
Data.head(15)

y_real  y_pred   y_probs
0        1       1  0.677159
1        0       0  0.068693
2        1       1  0.782068
3        0       0  0.062909
4        1       1  0.855969
5        0       0  0.180380
6        1       0  0.097364
7        0       1  0.694393
8        1       1  0.694412
9        1       0  0.059414
10       0       0  0.221712
11       1       1  0.864799
12       0       1  0.732394
13       1       1  0.633894
14       1       1  0.609831

In [57]:
#Confusion matrixe baxaq
##Confusion matrix pythonda by default basga formatda gelir
confusion_matrix(y, y_pred).T

array([[446, 119],
       [ 54, 149]])

In [58]:
##Confusion matrixi anlaya bileceyimiz formata saliriq
cm = confusion_matrix(y, y_pred).T
cm = pd.DataFrame(cm)
a0 = pd.DataFrame(cm[0])
a1 = pd.DataFrame(cm[1])
cm = pd.concat([a1,a0],axis = 1)
lst = [1,0]
cm = cm.loc[lst]
cm

1    0
1  149   54
0  119  446

In [59]:
data2 = pd.DataFrame(({'1' : ["TP" , "FN"] ,
          '0' : ['FP' , 'TN']}))
data2

1   0
0  TP  FP
1  FN  TN

#Let's calculate the Accuracy value (true  predictions / all predictions ---- 77% of our predictions are correct):
#(TP+TN)/(TP+TN+FP+FN)


In [60]:
y_pred = [1 if i > 0.5 else 0 for i in y_probs]

In [61]:
accuracy_score(y, y_pred)

0.7747395833333334

#Precision --- What percentage of what we predict as diabetes is actually diabetes?
# TP/(TP+FP)

In [62]:
print(precision_score(y,y_pred))
print(149/(149+54))

0.7339901477832512
0.7339901477832512


#Recall -  Sensitivity  -- True Pozitive rate --  - What percentage of people with diabetes were actually predicted to be diabetic?
#TP/(TP+FN)

In [63]:
print(recall_score(y,y_pred))
print(149/(149+119))

0.5559701492537313
0.5559701492537313


# F1 Skoru --  2 * (Presicion * recall)/(Presicion + recall)
#Balanced presicion and recall


In [64]:
f1_score(y,y_pred)

0.6326963906581741

In [65]:
#split dataset to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.30,
                                                    random_state = 42)

In [66]:
##Create model with train
loj = LogisticRegression(solver = "liblinear")
loj_model = loj.fit(X_train,y_train)
loj_model

LogisticRegression(solver='liblinear')

In [67]:
#  train accuracy
accuracy_score(y_train, loj_model.predict(X_train))


0.7802607076350093

In [68]:
##Calculate Accuracy of test
accuracy_score(y_test, loj_model.predict(X_test))

0.7489177489177489